export const useStyles = theme => ({
    loader: {
        position: 'absolute',
        top: 'calc(50% - calc(100px / 2))',
        left: 'calc(50% - calc(100px / 2))',
        border: `3px solid ${theme.palette.secondary.main}`,
        width: '100px',
        height: '100px',
        borderRadius: '50%',
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        animation: '$rotate 2s cubic-bezier(0.26, 1.36, 0.74,-0.29) infinite',
        transform: 'translateX(-50%) translateY(-50%)',
        '-webkit-transform': 'translateX(-50%) translateY(-50%)',
        '-moz-transform': 'translateX(-50%) translateY(-50%)',
        '-ms-transform': 'translateX(-50%) translateY(-50%)',
        '-o-transform': 'translateX(-50%) translateY(-50%)',
    },
    loader2: {
        position: 'absolute',
        top: 'calc(50% - calc(120px / 2))',
        left: 'calc(50% - calc(120px / 2))',
        border: `3px solid ${theme.palette.primary.main}`,
        width: 120,
        height: 120,
        borderRadius: '50%',
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        animation: '$rotate2 2s cubic-bezier(0.26, 1.36, 0.74,-0.29) infinite',
        transform: 'translateX(-50%) translateY(-50%)',
        '-webkit-transform': 'translateX(-50%) translateY(-50%)',
        '-moz-transform': 'translateX(-50%) translateY(-50%)',
        '-ms-transform': 'translateX(-50%) translateY(-50%)',
        '-o-transform': 'translateX(-50%) translateY(-50%)',
    },
    loader3: {
        position: 'absolute',
        top: 'calc(50% - calc(140px / 2))',
        left: 'calc(50% - calc(140px / 2))',
        border: `3px solid ${theme.palette.secondary.main}`,
        width: 140,
        height: 140,
        borderRadius: '50%',
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        animation: '$rotate 2s cubic-bezier(0.26, 1.36, 0.74,-0.29) infinite',
        transform: 'translateX(-50%) translateY(-50%)',
        '-webkit-transform': 'translateX(-50%) translateY(-50%)',
        '-moz-transform': 'translateX(-50%) translateY(-50%)',
        '-ms-transform': 'translateX(-50%) translateY(-50%)',
        '-o-transform': 'translateX(-50%) translateY(-50%)',
    },
    loader4: {
        position: 'absolute',
        top: 'calc(50% - calc(160px / 2))',
        left: 'calc(50% - calc(160px / 2))',
        border: `3px solid ${theme.palette.primary.main}`,
        width: 160,
        height: 160,
        borderRadius: '50%',
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        animation: '$rotate2 2s cubic-bezier(0.26, 1.36, 0.74,-0.29) infinite',
        transform: 'translateX(-50%) translateY(-50%)',
        '-webkit-transform': 'translateX(-50%) translateY(-50%)',
        '-moz-transform': 'translateX(-50%) translateY(-50%)',
        '-ms-transform': 'translateX(-50%) translateY(-50%)',
        '-o-transform': 'translateX(-50%) translateY(-50%)',
    },
    text: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        fontFamily: 'Arial',
        fontSize: 16,
        transform: 'translateX(-50%) translateY(-50%)',
        '-webkit-transform': 'translateX(-50%) translateY(-50%)',
        '-moz-transform': 'translateX(-50%) translateY(-50%)',
        '-ms-transform': 'translateX(-50%) translateY(-50%)',
        '-o-transform': 'translateX(-50%) translateY(-50%)',
    },
    "@global": {
        "@keyframes rotate": {
            '0%': { transform: 'rotateZ(-360deg)' },
            '100%': { transform: 'rotateZ(0deg)' }
        },
        "@keyframes rotate2": {
            '0%': { transform: 'rotateZ(360deg)' },
            '100%': { transform: 'rotateZ(0deg)' }
        }
    } 
});
